// Data layer: pull every markdown file in debrief/ in at build/dev time.
// Vite watches them, so editing memory hot-reloads the viewer.

// Code-provenance layer (generated by debrief/.system/build-provenance.mjs):
// session → repo → file → function, auto-derived from git.
import provenanceData from '../../provenance.json';
import { type Highlight, parseHighlights } from './parse-highlights';

export type {
  Highlight,
  HighlightSource,
  ParsedHighlights,
} from './parse-highlights';

export interface ProvFile {
  path: string;
  adds: number;
  dels: number;
  functions: string[];
}
export interface ProvRepo {
  repo: string;
  shas: string[];
  files: ProvFile[];
  fileCount: number;
  fnCount: number;
}
export interface ProvSession {
  docId: string;
  date: string | null;
  title: string;
  prs: Record<string, string[]>;
  repos: ProvRepo[];
}
export interface Provenance {
  generatedNote: string;
  builtFrom: string;
  sessions: ProvSession[];
}

export const provenance = provenanceData as Provenance;

const topLevel = import.meta.glob('../../*.md', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>;

const sessionFiles = import.meta.glob('../../sessions/**/*.md', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>;

export type DocKind = 'index' | 'readme' | 'highlights' | 'daily' | 'session';

export interface Doc {
  id: string;
  kind: DocKind;
  /** Path relative to debrief/ (for display). */
  path: string;
  title: string;
  /** YYYY-MM-DD when derivable. */
  date: string | null;
  /** Session frontmatter status (curated / machine-draft), sessions only. */
  status: string | null;
  archived: boolean;
  /** Markdown with frontmatter stripped. */
  content: string;
  entities: string[];
}

const WIKILINK = /\[\[([^\]|]+)\]\]/g;

function stripFrontmatter(raw: string): { body: string; status: string | null } {
  if (!raw.startsWith('---')) return { body: raw, status: null };
  const end = raw.indexOf('\n---', 3);
  if (end === -1) return { body: raw, status: null };
  const fm = raw.slice(3, end);
  const status = /status:\s*(\S+)/.exec(fm)?.[1] ?? null;
  return { body: raw.slice(end + 4).replace(/^\s*\n/, ''), status };
}

function titleOf(body: string, fallback: string): string {
  const m = /^#\s+(.+)$/m.exec(body);
  return m ? m[1].trim() : fallback;
}

function entitiesOf(body: string): string[] {
  const found = new Set<string>();
  for (const m of body.matchAll(WIKILINK)) found.add(m[1].trim());
  return [...found].sort();
}

function buildDocs(): Doc[] {
  const docs: Doc[] = [];
  for (const [file, raw] of Object.entries(topLevel)) {
    const name = file.split('/').pop() ?? file;
    const { body, status } = stripFrontmatter(raw);
    const dateMatch = /^(\d{4}-\d{2}-\d{2})/.exec(name);
    // HIGHLIGHTS.md must be named before the 'daily' fallback: it is undated, so
    // the !dateMatch guard below would otherwise drop the starred layer entirely.
    const kind: DocKind =
      name === 'INDEX.md'
        ? 'index'
        : name === 'README.md'
          ? 'readme'
          : name === 'HIGHLIGHTS.md'
            ? 'highlights'
            : 'daily';
    if (kind === 'daily' && !dateMatch) continue; // stray notes (e.g. .txt-adjacent)
    docs.push({
      id: name,
      kind,
      path: name,
      title: titleOf(body, name),
      date: dateMatch?.[1] ?? null,
      status,
      archived: false,
      content: body,
      entities: entitiesOf(body),
    });
  }
  for (const [file, raw] of Object.entries(sessionFiles)) {
    const rel = file.replace(/^\.\.\/\.\.\//, '');
    const name = file.split('/').pop() ?? file;
    const { body, status } = stripFrontmatter(raw);
    const dateMatch = /sessions\/(?:archive\/)?(\d{4}-\d{2}-\d{2})\//.exec(rel);
    docs.push({
      id: rel,
      kind: 'session',
      path: rel,
      title: titleOf(body, name),
      date: dateMatch?.[1] ?? null,
      status,
      archived: rel.includes('/archive/'),
      content: body,
      entities: entitiesOf(body),
    });
  }
  return docs;
}

export const docs: Doc[] = buildDocs();

export const dailies = docs
  .filter((d) => d.kind === 'daily')
  .sort((a, b) => (b.date ?? '').localeCompare(a.date ?? ''));

export const sessions = docs
  .filter((d) => d.kind === 'session')
  .sort((a, b) => b.id.localeCompare(a.id));

export const indexDoc = docs.find((d) => d.kind === 'index') ?? null;

/** The ★ starred layer. Null until the store has a HIGHLIGHTS.md. */
export const highlightsDoc = docs.find((d) => d.kind === 'highlights') ?? null;

const parsedHighlights = parseHighlights(highlightsDoc?.content);

/**
 * The starred entries, real ones first. Empty when HIGHLIGHTS.md is absent,
 * empty, or shaped in a way the parser does not recognise — callers fall back
 * to rendering `highlightsDoc` raw, so the tab is never blank.
 */
export const highlights: Highlight[] = parsedHighlights.entries;

/** The scaffolding around the list: intro, the two rules, how-to, recall. */
export const highlightsAbout: string = parsedHighlights.about;

/** entity → docs that mention it (dailies + sessions only). */
export const entityMap: Map<string, Doc[]> = (() => {
  const m = new Map<string, Doc[]>();
  for (const d of docs) {
    if (d.kind === 'readme') continue;
    for (const e of d.entities) {
      const list = m.get(e) ?? [];
      list.push(d);
      m.set(e, list);
    }
  }
  return m;
})();
